"""add hashed_password to users

Revision ID: 67bbeef7cd38
Revises: be5a4dfeb518
Create Date: 2026-03-26 22:35:30.082257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bbeef7cd38'
down_revision: Union[str, Sequence[str], None] = 'be5a4dfeb518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
